version: '3.8'

services:
  # React Application
  web:
    container_name: emge-art-react-web
    image: samreiss/emge-art-react-web:latest
    ports:
      - "3010:80"
    environment:
      - REACT_APP_LOGGING_ENABLED=true
    restart: always
