name: Deploy to Azure App Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: samreiss/emge-art-react-web:latest
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        login-server: index.docker.io

    # Update the deployment date
    - name: Update last successful deployment date
      run: |
        echo "{ \"date\": \"$(date -u +'%Y-%m-%d %H:%M UTC')\" }" > last_successful_deployment.json

    # Commit and push the date file
    - name: Commit last deployment date
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update last successful deployment date"
        file_pattern: last_successful_deployment.json