name: Deploy to Azure App Service

on:
  workflow_dispatch: # Allows manual trigger without branch selection
    inputs:
      trigger:
        description: "Manually Trigger Deployment to Azure App Service"
        
  workflow_run:
    workflows: ["Publish to Docker Hub"]
    types:
      - completed 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: samreiss/emge-art-react-web:latest
          resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP }}